# These settings are meant to apply changes across the whole site. Some more
# hidden settings have also been brought up to this level to make the site 
# easier to administer.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UF Data Science and Informatics
email: your-email@domain.com
description: > # the greater-than means to ignore newlines until "baseurl:"
  The UF Data Science and Informatics Student Organization
baseurl: "/www.dsiufl.org-2016" # the subpath of your site, e.g. /blog
url: "http://dsiufl.github.io" # the base hostname & protocol for your site
twitter_username: dsiufl
github_username:  dsiufl
carousel_interval: 10000

# Build settings
markdown: kramdown

# Collections
collections:
  members:
    output: true
    permalink: /members/:path/
